version: '3'

services:
  streamlit_web_page:
    build:
      context: ../Dockerfile/streamlit
      dockerfile: Dockerfile
    image: streamlit
    container_name: streamlit_web_page
    volumes:
      - ../src_streamlit_server:/app/src
    working_dir: /app
    # ports:
    #   - "8000:8000"
    tty: true
    entrypoint: sh -c "cd /app/src && streamlit run main.py --server.headless true --server.enableCORS false --server.enableXsrfProtection false"

  fastapi_web_page:
    build:
      context: ../Dockerfile/FastAPI
      dockerfile: Dockerfile
    image: fastapi
    container_name: fastapi_web_page
    volumes:
      - ../src_fastapi_server:/app/src
    working_dir: /app
    # ports:
    #   - "9000:9000"
    tty: true
    entrypoint: sh -c "cd /app/src && uvicorn main:app --host 0.0.0.0 --reload --port 9000"

  nginx:
    image: nginx:1.21
    container_name: nginx
    ports:
      - "80:80"
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - streamlit_web_page
      - fastapi_web_page
    volumes:
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
